Feature/contacts
MonikaJablonska/ice-cream-5makers pull request #7
Opened 2022-03-17 15:06 UTC by BartlomiejKita

hello! finished mobile/tablet/desktop contact section, also added sprite.svg file to add icons there.

2022-03-17 17:33 UTC, MonikaJablonska commented
Hej @BartlomiejKita, ustaw sobie Reviewera, żeby zrobił Ci codereview :)

2022-03-17 21:41 UTC, MonikaJablonska requested changes

2022-03-18 12:22 UTC, BartlomiejKita commented on src/partials/contacts.html
> +          <use href="../src/images/sprite.svg#arrow"></use>
już próbowałem wcześniej i mi nie działało :(

2022-03-18 12:26 UTC, BartlomiejKita commented on src/sass/_contacts.scss
> +    stroke: #d41342;
done

2022-03-18 12:36 UTC, MonikaJablonska approved these changes

2022-03-18 12:36 UTC, merged